service: glowhkb
image: djnoopnoop/glowhkb

servers:
  web:
    - 167.172.27.4

proxy:
  ssl: true
  host: glowhkb.net
  app_port: 3000

registry:
  server: localhost:5555

builder:
  arch: amd64

env:
  clear:
    DB_HOST: db
    DB_PORT: 5432
    DB_USERNAME: postgres
  secret:
    - RAILS_MASTER_KEY
    - DB_PASSWORD

accessories:
  db:
    image: postgres:16
    host: 167.172.27.4
    port: 5432
    env:
      clear:
        POSTGRES_DB: glowhkb_production
        POSTGRES_USER: postgres
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data