service: glowhkb
image: djnoopnoop/glowhkb

servers:
  web:
    - 167.172.27.4

proxy:
  ssl: true
  host: glowhkb.net
  app_port: 3000

registry:
  server: localhost:5555

builder:
  arch: amd64

env:
  secret:
    - RAILS_MASTER_KEY